file.directory=files
spring.servlet.multipart.max-file-size=10MB
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/cars
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=2211
